- api/src/models/Admins.js
- api/src/models/Clients.js
Creé los modelos de Clientes y Admins
> Feat clients&admins model

- api/src/db.js
- api/src/models/Admins.js
- api/src/models/Categorys.js
- api/src/models/Clients.js
- api/src/models/Products.js
Creados modelos products y categorys
Creadas relaciones entre ambos
Arreglados los comentarios de los modelos Clients y Admins
> Feat products/categorys models

- client/src/App.jsx
- client/src/components/nav/Nav.jsx
[![codeNav.png](https://i.postimg.cc/CMP00szL/codeNav.png)](https://postimg.cc/MXQNbR7h)
> Component Nav with routs and conditional in App.jsx

- api/src/controllers/Comments/deleteComment.js
- api/src/controllers/Comments/getCommentsByProductId.js
- api/src/controllers/Comments/postComment.js
- api/src/controllers/Comments/putComment.js
- api/src/db.js
- api/src/handlers/comments-routes.js
- api/src/routes/index.js
- api/src/validations/validationComment.js
Rutas Comentarios:
-GET - /comments/:productId (devuelve todos los comentarios de un producto)
-POST - /comments/:productId/:clientId (crea un comentario para un producto)
-PUT - /comments/:id (Permite modificar un comentario existente)
-Delete - /comments/:id (Permite borrar un comentario)
> Comments Routes

- api/src/controllers/Categories/getCategories.js
- api/src/controllers/Comments/postComment.js
- api/src/controllers/Profesionals/getProfesionalDetail.js
- api/src/controllers/Profesionals/postProfesional.js
- api/src/controllers/Services/getServices.js
- api/src/controllers/Services/postService.js
- api/src/handlers/profesionals-routes.js
- api/src/handlers/service-routes.js
- api/src/validations/ValidationService.js
- api/src/validations/professionalsValidation.js
Creacion de valdiaciones para rutas Profesionals y Services
Errores personalizados con cada error que pudiera surgir
> Feature/errors messages/franco

- api/src/controllers/Categories/getCategories.js
- api/src/controllers/Clients/postClient.js
- api/src/controllers/Clients/putClientInfo.js
- api/src/controllers/Profesionals/getProfesionalDetail.js
- api/src/handlers/categories-routes.js
- api/src/handlers/client-routes.js
- api/src/validations/validationCategories.js
- api/src/validations/validationClient.js
Validaciones para clientes y categorias
Nueva ruta para modificar datos de usuario (adress y phone)
> Validations for categories and clients + new route for clients

- api/package.json
- api/src/controllers/Services/getServices.js
- api/src/validations/ValidationService.js
- api/test/routes/Comments/comments.spec.js
- api/test/routes/Comments/commentsData.js
- api/test/routes/Services/serviceData.json
- api/test/routes/Services/serviceTest.spec.js
Armado de tests para las rutas comments y services.
Genera informacion en la base de datos, testea todas las rutas con esa informacion y al terminar el test se eleimina la informacion creada
> Tests for Comments routes and services routes

- api/src/controllers/Products/getProducts.js
- api/src/data/productos.json
- client/src/components/paginations/Paginations.jsx
- client/src/components/searchBar/SearchBar.jsx
- client/src/components/showCardsProduct/ShowCardsProduct.jsx
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/views/products/Products.jsx
Agregado de productos en productos.json
arreglado bug de op en controller getProducts
creado de action getProductByName y su reducer
creado de searchBar para que busque por nombre
> SearchBar 

- client/src/views/landing/Landing.jsx
- client/src/views/landing/Landing.module.css
Arregle un error en la landing con los estilos de los textos :)
> fix landing css problems

- client/src/App.jsx
- client/src/components/filter/Filter.jsx
- client/src/components/order/Order.jsx
- client/src/components/searchBar/SearchBar.jsx
- client/src/hooks/useGetCategories.js
- client/src/hooks/useToggle.js
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/request/category.js
- client/src/utils/filterProducts.js
- client/src/views/home/Home.jsx
- client/src/views/products/Products.jsx
- client/src/views/services/Services.jsx
Creado de ordenamiento y filtrado
> filtros y ordenamientos

- client/src/App.jsx
- client/src/components/formCreateProduct/FormCreateProduct.jsx
- client/src/request/product.js
- client/src/utils/validateCreateProduct.js
- client/src/views/home/Home.jsx
- client/src/views/newProduct/NewProduct.jsx
Se creo el formulario para agregar productos
> Se creo el formulario para creacion de producto

- client/src/components/filter/Filter.jsx
- client/src/components/paginations/Paginations.jsx
- client/src/components/paginations/Paginations.module.css
- client/src/components/searchBar/SearchBar.jsx
- client/src/components/searchBar/SearchBar.module.css
- client/src/components/showCardsProduct/ShowCardsProduct.module.css
- client/src/views/products/Products.jsx
- client/src/views/products/Products.module.css
Estilizado a los botones y centrado de cards en Products
> Estilizado a los botones y centrado de cards en Products

- client/src/components/card/Card.jsx
- client/src/components/card/Card.module.css
- client/src/components/showCardsProduct/ShowCardsProduct.module.css
> estilos de cards arreglados

- api/src/controllers/Categories/deleteCategory.js
- api/src/controllers/Categories/postCategory.js
- api/src/controllers/Categories/putCategory.js
- api/src/controllers/Clients/postClient.js
- api/src/controllers/Developers/postDeveloper.js
- api/src/controllers/Products/postProduct.js
- api/src/controllers/Products/updateProduct.js
- api/src/controllers/Profesionals/postProfesional.js
- api/src/controllers/Profesionals/putProfesional.js
- api/src/controllers/Services/postService.js
- api/src/data/productos.json
- api/src/data/productsData.js
- api/src/handlers/categories-routes.js
- api/src/validations/deleteCategory.js
- api/src/validations/postCategory.js
- api/src/validations/putCategory.js
- api/src/validations/updateProduct.js
Terminé el CRUD de categories y agregué el detalle de que cuando posteen un producto o cualquier otra cosa los strings empiezen siempre con mayúscula
> Category crud

- client/src/components/card/Card.module.css
- client/src/components/filter/Filter.jsx
- client/src/components/filter/Filter.module.css
- client/src/components/order/Order.jsx
- client/src/components/order/Order.module.css
- client/src/components/paginations/Paginations.jsx
- client/src/components/paginations/Paginations.module.css
- client/src/components/searchBar/SearchBar.jsx
- client/src/components/searchBar/SearchBar.module.css
- client/src/components/showCardsProduct/ShowCardsProduct.module.css
- client/src/index.css
- client/src/views/products/Products.jsx
- client/src/views/products/Products.module.css
Cambie estilosde home, agregue order.module.css
> Feature styles2.0

- client/package.json
- client/src/components/promo card/PromoCard.jsx
- client/src/components/promo card/PromoCard.module.css
- client/src/views/home/Home.jsx
- client/src/views/home/Home.module.css
agregue estilos y la libreria de Splide para hacer el carrousel
> deje home bien facherito

- client/src/components/formCreateProduct/FormCreateProduct.jsx
- client/src/components/formCreateProduct/FormCreateProduct.module.css
- client/src/components/inputForm/InputForm.jsx
- client/src/components/inputForm/InputForm.module.css
- client/src/components/nav/Nav.jsx
- client/src/views/detailProduct/DetailProduct.jsx
- client/src/views/detailProduct/DetailProduct.module.css
- client/src/views/home/Home.jsx
Se termino el css view admin create product
> CSS Create Product

- client/src/views/about/About.jsx
- client/src/views/about/About.module.css
> estilos de about

- api/src/controllers/Appointments/deleteAppointment.js
- api/src/controllers/Appointments/getAppoinmentsByClient.js
- api/src/controllers/Appointments/getAppointmentsByAdmin.js
- api/src/controllers/Appointments/getAppointmentsByProfesional.js
- api/src/controllers/Appointments/getAppointmentsByService.js
- api/src/controllers/Appointments/postAppointmentByClient.js
- api/src/controllers/Appointments/updateAppointment.js
- api/src/controllers/Clients/postClient.js
- api/src/data/productos.json
- api/src/db.js
- api/src/handlers/appointments-routes.js
- api/src/models/Appointments.js
- api/src/routes/index.js
- api/src/validations/postAppointment.js
- api/src/validations/validationAppointment.js
- api/src/validations/validationUpdateAppointment.js
*Para Crear Appointments: ruta: POST("/appointments") forma del objeto json: 
{
"profesionalId":1,
"clientId":7,
"serviceId":1,
"date": "2023-05-15",
"hour": "13:30:00"
}
*para actualizar Appointments : PATCH(/appointments/appoinmentID) el cuerpo del json : 
ejemplo: {
"ProfesionalId":4,
"ServiceId":4,
"date": "2023-08-15",
"hour": "00:30:00"
}
> Creacion de la ruta y modelos de Appointments

- client/package.json
- client/src/components/dragImage/DragImage.jsx
- client/src/components/dragImage/DragImage.module.css
- client/src/components/formCreateProduct/FormCreateProduct.jsx
- client/src/components/inputImage/inputImage.jsx
- client/src/components/inputImage/inputImage.module.css
- client/src/utils/firebaseConfig.js
> Feature storage image

- client/src/components/order/Order.jsx
Cambio de order input de select a radio
> Cambio de order input de select a radio

- client/src/handlers/handleSubmitLogin.js
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/request/clients.js
- client/src/utils/firebaseConfig.js
- client/src/views/landing/Landing.jsx
Creación de usuario con firebase
> Creado de login con firebase

- client/src/components/buttons/Button-accent1/Button-accent1.jsx
- client/src/components/buttons/Button-accent1/Button-accent1.module.css
- client/src/components/card/Card.module.css
- client/src/components/nav/Nav.jsx
- client/src/components/nav/Nav.module.css
- client/src/components/paginations/Paginations.module.css
- client/src/views/cart/Cart.jsx
agregue la logica de mercado pago
> Feature mercadopago front

- api/src/controllers/Clients/postClient.js
- client/src/App.jsx
- client/src/components/login/Login.jsx
- client/src/components/nav/Nav.jsx
- client/src/components/protectedRoute/ProtectedRoute.jsx
- client/src/handlers/handleSubmitLogin.js
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/views/about/About.module.css
- client/src/views/detailProduct/DetailProduct.jsx
- client/src/views/landing/Landing.jsx
- client/src/views/landing/Landing.module.css
Creado el login componetizado y las rutas protegidas segun el usuario
> Creado el login componetizado y las rutas protegidas segun el usuario

- client/src/components/card/Card.jsx
- client/src/components/card/Card.module.css
- client/src/components/imageComponent/ImageComponent.jsx
- client/src/components/nav/Nav.jsx
- client/src/components/nav/Nav.module.css
- client/src/views/detailProduct/DetailProduct.jsx
cambios:
CARD:
- los precios de las cards ya no se deberian cortar
- los nombresd e ms de 13 caracteres tienen '...' 
- agregue hover a las cards con un scale
NAVBAR:
- estilos al boton de login
PROD DETAIL:
- la flecha de back ahora lleva a products en lugar de home
>  estilos varios cambiados

- client/src/views/cart/Cart.jsx
parte front de  mercado pago en cart.jsx, mando al front :
id
name ( el back lo recibe title )
id
quantity
unit_price
- todo sacado desde el localStorage
> Feat mercadopago front

- client/src/App.jsx
- client/src/views/cart/Cart.jsx
- client/src/views/cart/Cart.module.css
- client/src/views/detailProduct/DetailProduct.jsx
Reverts Niitram/pf-beautify#105
> Revert "Feat/vivi cart"

- client/src/components/sectionCards/SectionCards.jsx
- client/src/components/sectionCards/SectionCards.module.css
- client/src/utils/getProductsCategorie.js
- client/src/utils/getTopRatedProducts.js
- client/src/views/detailProduct/DetailProduct.jsx
- client/src/views/home/Home.jsx
Se creo un componente el cual muestra 5 cards según si se le pide que muestre los mas populares o una categoria y muestra las mas populares de esa categoria
> Creado del componente SectionCards

- client/src/components/nav/Nav.jsx
- client/src/components/searchBar/SearchBar.module.css
- client/src/views/landing/Landing.module.css
- client/src/views/products/Products.module.css
cambie estilos y algunas cosas que se veian mal:
- la searchbar se cortaba y tenia en todos los border un border-radius.
- se habia borrado el background color en la landing
- agregue un boton home ademas del logo
> cambie algunas cositas de diferentes estilos

- client/src/App.jsx
- client/src/components/AlertWarning/AlertWarning.jsx
- client/src/components/AlertWarning/AlertWarning.module.css
- client/src/handlers/handleSearch.js
- client/src/handlers/handleSubmitCreate.js
- client/src/handlers/handleSubmitLogin.js
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/views/home/Home.jsx
- Creado de un componente Alert para mostrar los errores al cual se ejecuta al dispachar la action showError  
- A esta action showError se le pasa un objeto con un tittle y  un mesagge que se mostrara en el alert
- Agregado el alert en varios catch de los handlers (Si encuentran algun catch sin el alert agregenselo por favor)
> Created Alert

- api/index.js
- api/src/controllers/MercadoPago/approved.js
- api/src/controllers/Shops/postNewShop.js
- api/src/handlers/mercadoPago-routes.js
- api/src/models/purchaseCart.js
Integracion de mercado pago (back)
> Mercado Pago v 1.0

- client/src/components/login/Login.jsx
- client/src/components/nav/Nav.jsx
- client/src/components/paginations/Paginations.jsx
- client/src/components/paginations/Paginations.module.css
- client/src/handlers/handleSubmitLogin.js
- client/src/views/detailProduct/DetailProduct.jsx
- client/src/views/detailProduct/DetailProduct.module.css
- client/src/views/landing/Landing.jsx
- client/src/views/landing/Landing.module.css
Estilos:
- product detail tiene el mismo fondo rosita que el resto de la pagina
- comente el boton de services en la navbar por el momento
- en el paginado nos muestra en que pagina estamos actualmente
- modifique los estilos en los botones de log in para que sean distintos
- al hacer hover estos botones agregan flechitas :)
Funcionalidades:
- al hacer enter en el form de log in ya no se cierra
> estilos y funcionalidad en landing y otros

- client/src/components/nav/Nav.jsx
- client/src/components/nav/Nav.module.css
Estilos responsive de la NavBar
> estilos navbar

- api/package.json
- api/src/config-email/account-transporter.json
- api/src/config-email/nodemailer.js
- api/src/config-email/sendMail.js
- api/src/config-email/sendMailByShop.js
- api/src/controllers/Clients/postClient.js
- api/src/controllers/Shops/postNewShop.js
[*todo esta en la carpeta config-email,ruta relativa desde api: ./src/config-email alli se agregaron archivos de configuracion y sus funciones.]
>  configuracion para el envio de correos al registrarse como usuario y realizar compra

- client/src/App.jsx
- client/src/components/buttons/Button-accent1/Button-accent1.jsx
- client/src/components/login/Login.jsx
- client/src/components/login/Login.module.css
- client/src/handlers/handleSubmitLogin.js
- client/src/utils/firebaseConfig.js
- client/src/views/home/Home.module.css
Arreglado de bug en login y modificado de estilos
> Arreglado de bug en login y modificado de estilos

- client/src/views/cart/Cart.jsx
- client/src/views/cart/Cart.module.css
solo cambie estilos en la lista de los productos en el carrito y del boton de checkout
>  mini pr para carrito

- api/src/handlers/mercadoPago-routes.js
- client/src/components/buttons/buttonNav/buttonNav.module.css
- client/src/components/footerAll/FooterAll.module.css
- client/src/components/nav/Nav.jsx
- client/src/components/nav/Nav.module.css
- client/src/views/Checkout/Checkout.jsx
- client/src/views/Checkout/Checkout.module.css
- client/src/views/about/About.jsx
- client/src/views/about/About.module.css
- client/src/views/cart/Cart.module.css
comente el footer en about
cambie la ruta de mercado pago que no redireccionaba bien
estilos de checkout
> pr monumental

- client/src/App.jsx
- client/src/components/login/Login.jsx
- client/src/components/login/Login.module.css
- client/src/components/login/passwordSecurity/PasswordSecurity.jsx
- client/src/components/login/passwordSecurity/PasswordSecurity.module.css
- client/src/utils/firebaseConfig.js
- client/src/utils/validateCreateUser.js
- client/src/utils/validateUpdateUser.js
- client/src/views/detailProduct/DetailProduct.jsx
- client/src/views/detailUser/DetailUser.jsx
- client/src/views/detailUser/DetailUser.module.css
Corregí algunos errores de validaciones al actualizar usuario
cambié la regex que valida la dirección y el nombre para que permita acentos
Agregué la verificación de seguridad del password
Arreglé algunos desperfectos de estilos
> Fix detail user validations

- client/src/components/card/Card.jsx
- client/src/components/slideDialog/slideDialog.jsx
- client/src/redux/actions.js
- client/src/views/cart/Cart.jsx
- client/src/views/detailProduct/DetailProduct.jsx
- client/src/views/detailUser/DetailUser.jsx
- client/src/views/favorites/Favorites.jsx
confirmar que quiera eliminar artículo del carrito 
confirmar la compra antes de pasar a la pasarela de pagos
favoritos (si no hay, que no se abra, pop up)
rellenar el corazón cuando se agrega a favorito en el detalle del producto
que el botón de favoritos sirva para eliminar favoritos
que te redirija si no hay favoritos
> Fix demo bugs

- client/src/components/buttons/buttonNav/buttonNav.module.css
- client/src/components/footerAll/FooterAll.jsx
- client/src/components/footerAll/FooterAll.module.css
- client/src/views/Checkout/Checkout.jsx
- client/src/views/Checkout/Checkout.module.css
- client/src/views/home/Home.jsx
saque del checkout los tax y shipping
saque el lorem del home y puse un texto cualquiera
corregi el movimiento que tenian los botones de la navbar
redisene el footer e inclui la  redirecction a developers
> arreglos de la demo en estilos

- api/src/controllers/Clients/purchaseDevolution.js
- api/src/controllers/Products/addStock.js
- api/src/controllers/Services/getServices.js
- api/src/controllers/Services/postService.js
- api/src/data/services.js
- api/src/data/services.json
- api/src/handlers/client-routes.js
- api/src/handlers/contact-routes.js
- api/src/handlers/service-routes.js
- api/src/models/Appointments.js
- api/src/models/Clients.js
- api/src/models/Services.js
- api/src/validations/ValidationService.js
- api/src/validations/validationClient.js
Nueva ruta para devoluciones
Validación para ruta devoluciones
Agregado balance en modelo clientes
Agregada duración en modelo servicios
Agregada entrada paid (boolean) a modelo appointments
> Devolutions route

- api/src/controllers/Shops/getShopsByClient.js
- api/src/data/allDataFunctions.js
- api/src/data/appointments.js
- api/src/data/appointments.json
- api/src/data/productsData.js
- client/src/App.jsx
- client/src/handlers/handleGetUserDataForHistory.js
- client/src/request/appointments.js
- client/src/request/clients.js
- client/src/views/detailUser/DetailUser.jsx
- client/src/views/userHistory/UserHistory.jsx
Creé la vista userHistory, con su correspondiente ruta (protegida)
Creé la función que trae las compras y las citas de la base de datos y calcula si el cliente está a tiempo de cancelarlas
> Feature client history

- .vscode/settings.json
- client/src/views/Checkout/Checkout.jsx
- client/src/views/about/About.jsx
- client/src/views/favorites/Favorites.jsx
- client/src/views/home/Home.jsx
- client/src/views/landing/Landing.jsx
- client/src/views/landing/Landing.module.css
- client/src/views/products/Products.jsx
Landing responsive
se quito el Footer de todas las paginas que aparece
> Fix responsive

- api/src/controllers/Comments/postServiceComment.js
- api/src/controllers/Services/getServiceData.js
- api/src/data/clients.json
- api/src/db.js
- api/src/handlers/comments-routes.js
- api/src/handlers/service-routes.js
- api/src/models/Comments.js
Ruta para traer servicio por ID y sus comentarios
Ruta para comentar sobre servicios: require por body: 	
- "tittle": "Comentario del cliente 5" (requerido)
-"content": "Testttt" (requerido)
- "rating": 1 (no requerido, default: 1)
> Service routes update

- client/src/components/calendar/Calendar.jsx
- client/src/components/calendar/Calendar.module.css
- client/src/components/linearStepper/LinearStepper.jsx
- client/src/components/nav/Nav.jsx
Agregado de un LinearStepper y descripcion de lo que el usario va eligiendo para que el cliente comprenda mejor el flujo del calendario
> Agregado de un LinearStepper

- client/src/App.jsx
- client/src/components/footerAll/FooterAll.jsx
- client/src/components/footerAll/FooterAll.module.css
- client/src/views/home/Home.jsx
- client/src/views/home/Home.module.css
se modifico el font del footer
de agrego el carrusel en home
> Estilos responsive

- api/src/controllers/Appointments/getAppointmentsByServiceAndDate.js
- api/src/handlers/appointments-routes.js
ejemplo del resultado: al llamar a la ruta get de appointment segun el servicio y la fecha
GET: http://localhost:3001/appointments/service/1/date/2023-05-26
resultado: 
[
{
"hour": "09:00:00",
"available": true
},
{
"hour": "10:15:00",
"available": false
},
{
"hour": "11:30:00",
"available": true
},
{
"hour": "14:00:00",
"available": true
},
{
"hour": "16:15:00",
"available": true
},
{
"hour": "17:30:00",
"available": true
},
{
"hour": "18:45:00",
"available": true
}
]    NOTA: TRUE corresponde a los horarios disponibles y FALSE a los que están reservados según la fecha.
> se agrego una ruta nueva en la ruta appointment para que devuelva los horarios disponibles 

- client/src/App.jsx
- client/src/components/ClientsTable/ClientsTable.jsx
- client/src/components/ProductsTable/ProductsTable.jsx
- client/src/components/ProductsTable/ProductsTable.module.css
- client/src/views/ProductDetailAdmin/ProductDetailAdmin.module.css
- client/src/views/ProductDetailAdmin/ProductsDetailAdmin.jsx
- client/src/views/ProductsAdmin/ProductsAdmin.jsx
- client/src/views/ProductsAdmin/ProductsAdmin.module.css
- cree la ruta product detail en app.jsx (para el admin)
- esta lista la tabla de productos, se ve todo y si apretas te lleva al detail donde,en un futuro, el admin va a poder acutalizar los precios stock y eso.
todavia no se puede editar nada y los estilos estan maomeno pero va queriendo :)
> products admin 1.0

- client/src/request/product.js
- client/src/utils/FilterEmptyProps.js
- client/src/views/ProductDetailAdmin/ProductDetailAdmin.module.css
- client/src/views/ProductDetailAdmin/ProductsDetailAdmin.jsx
- client/src/views/ProductsAdmin/ProductsAdmin.jsx
- client/src/views/ProductsAdmin/ProductsAdmin.module.css
- client/src/views/detailUser/DetailUser.module.css
- solucionado el bug del detail de producto desde el admin que crasheaba con el toFixed(2)
- agregue la request que se encarga de actualizar un producto
- agregue a utils una funcion que filtra las propiedades quetengan un string vacio en un objeto
- ya esta terminada (sin bugs hasta lo que probe) la tabla, el boton que lleva a anadir un producto al igual que la vista y modificacion de propiedades de un producto
- solucionado un bug que hacia que un estilo de input se aplique a todos
>  finished product detail and add from admin

- api/src/controllers/Profesionals/getProfesionals.js
- client/src/App.jsx
- client/src/components/FormCreateProfessional/FormCreateProfessional.jsx
- client/src/components/FormCreateProfessional/FormCreateProfessional.module.css
- client/src/components/ProfessionalsTable/ProfessionalsTable.jsx
- client/src/components/ProfessionalsTable/ProfessionalsTable.module.css
- client/src/request/professionals.js
- client/src/views/Professionals/Professionals.jsx
- client/src/views/Professionals/Professionals.module.css
- client/src/views/newProfessional/NewProfessional.jsx
- client/src/views/newProfessional/NewProfessional.module.css
- agregue peticion de getAllProfessionals
- getProfesiionals.js tira tambien la duracion del servicio
- tabla profesionales
-
> Feat profesionals

- client/src/App.jsx
- client/src/components/appointmentsTableAdmin/AppointmentsTableAdmin.jsx
- client/src/components/appointmentsTableAdmin/AppointmentsTableAdmin.module.css
- client/src/components/navAdmin/NavAdmin.jsx
- client/src/request/appointments.js
- client/src/views/Checkout/Checkout.jsx
- client/src/views/appointments/Appointments.jsx
- client/src/views/appointments/Appointments.module.css
- creada la view de appointments para el admin
- creada la tabla de appointments para el admin
- creada la request para traer todos los appointments
- navbar admin
- borre algunos console.logs que estaban en checkout
>  tabla de appointments

- api/src/controllers/Profesionals/getProfesionals.js
- api/src/controllers/Services/getServices.js
- client/src/App.jsx
- client/src/components/FormCreateProfessional/FormCreateProfessional.jsx
- client/src/components/FormCreateProfessional/FormCreateProfessional.module.css
- client/src/components/ProfessionalsTable/ProfessionalsTable.jsx
- client/src/components/appointmentsTableAdmin/AppointmentsTableAdmin.jsx
- client/src/components/appointmentsTableAdmin/AppointmentsTableAdmin.module.css
- client/src/components/navAdmin/NavAdmin.jsx
- client/src/components/servicesTable/ServicesTable.jsx
- client/src/components/servicesTable/ServicesTable.module.css
- client/src/request/appointments.js
- client/src/request/professionals.js
- client/src/utils/validateCreateProfessional.js
- client/src/views/Checkout/Checkout.jsx
- client/src/views/Services Control/ServicesControl.jsx
- client/src/views/Services Control/ServicesControl.module.css
- client/src/views/appointments/Appointments.jsx
- client/src/views/appointments/Appointments.module.css
perdon por el PR grande, parece que se arrastraron cosas del pr que hice antes, asi que voy a intentar ser lo mas explicativo posible sobre cosas que cambie **EN ESTE PR**:
- esta la tabla completa de servicios: muestra el servicio, la duracion y quien lo hace. por cuestiones de comodidad no se van a mostrar (por ahora) los appointments de cada servicio
- el controller de getServices() ahora trae el nombre del profesional que realiza el servicio, no su id
commit de cositas :
- el controller getProfessionals() trae los appointments que tiene cada profesional (dia y hora) al igual que el servicio que realiza, los appointmentsno se muestran por ahora en la tabla
- se puede crear un profesional **PERO** si o si se necesita que se le mande un servicio, cosa que todavia no hice asi que si creo …
> Feat services table

- api/src/controllers/Shops/getAllShopsDetails.js
- client/src/App.jsx
- client/src/components/ProductsTable/ProductsTable.jsx
- client/src/components/ProfessionalsTable/ProfessionalsTable.jsx
- client/src/components/appointmentsTableAdmin/AppointmentsTableAdmin.jsx
- client/src/components/navAdmin/NavAdmin.jsx
- client/src/components/salesTable/salesTable.jsx
- client/src/components/salesTable/salesTable.module.css
- client/src/request/shops.js
- client/src/views/ProductsAdmin/ProductsAdmin.jsx
- client/src/views/Professionals/Professionals.jsx
- client/src/views/Professionals/Professionals.module.css
- client/src/views/Sales/Sales.jsx
- client/src/views/Sales/sales.module.css
- client/src/views/dashboardAdmin/DashboardAdmin.jsx
perdon por el gran pr de vuelta, pense q iba a ser tranqui jajaja
FIXED:
- arreglado el estilo del ' + ' en todas las paginas de admin, antes se veia super mini
- agregado el boton home y sales en la navbar del admin
- la navbar del admin solo se ve en la cuenta del admin 
- corregido el wdit en las tablas de appointments para que no se corte nada
- discount ya no tiene ' %' en productos, ya que no es un porcentaje sino lo que se le resta
- getAllShopsDFetail() diferencia entre price y count
- la tabla de appointments tenia al revez los headers de profesional y cliente
FEATURE:
- vista de sales
- tabla de sales 
- request de todas las sales
> varias cositas

- client/src/App.jsx
- client/src/components/calendar/Calendar.jsx
- client/src/views/services/Services.jsx
Guests cannot make reservations
> Guests cannot make reservations

- client/src/components/dashboard/Resumen.jsx
- client/src/components/dashboard/Resumen.module.css
- client/src/components/filter/Filter.jsx
- client/src/components/filter/Filter.module.css
- client/src/components/searchBar/SearchBar.module.css
- client/src/components/slideDialog/slideDialog.jsx
- client/src/views/detailProduct/DetailProduct.module.css
- client/src/views/products/Products.jsx
- client/src/views/products/Products.module.css
responsive products
responsive detailProductos
> responsive products

- api/src/controllers/Profesionals/getProfesionalDetail.js
- client/src/App.jsx
- client/src/components/cardProfessional/CardProfessional.jsx
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/views/detailService/DetailService.jsx
- client/src/views/services/Services.jsx
- client/src/views/services/Services.module.css
Se renderizan las cards de lo profesionales en services
> Cards professionals service

- client/src/components/cardService/CardService.module.css
Arreglado de estilos en las card de servicios
> fix card styles

- client/src/components/login/Login.module.css
se hizo un ajuste para que el titulo WELCOME no se viera recortado y el formulario se viera un poquito mas ancho
> Retoque login

- client/src/App.jsx
- client/src/components/formCreateProduct/FormCreateProduct.jsx
- client/src/components/formCreateProduct/FormCreateProduct.module.css
- client/src/components/inputForm/InputForm.module.css
- client/src/views/cart/Cart.jsx
- client/src/views/cart/Cart.module.css
Se cambio detalles responsivo de CSS en Cart las Tarjetas de productos
> Fix cambios admin

- api/src/controllers/Appointments/postAppointmentByClient.js
- api/src/controllers/Clients/findOrCreateClient.js
- api/src/controllers/Clients/purchaseDevolution.js
- api/src/controllers/MercadoPago/approved.js
- api/src/controllers/Profesionals/postProfesional.js
- api/src/controllers/SavedCarts/postSavedCart.js
- api/src/controllers/Shops/cancelShop.js
- api/src/controllers/Shops/getAllShopsDetails.js
- api/src/controllers/Shops/getShopsByClient.js
- api/src/handlers/client-routes.js
- api/src/handlers/mercadoPago-routes.js
- client/src/views/cart/Cart.jsx
- client/src/views/checkoutAppointment/CheckoutAppointment.jsx
Fix en los mails de appoitnments. Ahora se envian!
> fix on appointments mails
